spring.application.name=spring-zeus

#openai.api.key=sk-xxxxx  # Coloque sua chave da OpenAI aqui
#spring.ai.openai.api-key=<your-openai-api-key>

#spring.ai.azure.openai.api-key=<your-openai-api-key>
#spring.ai.azure.openai.endpoint=<your-openai-api-key>
#spring.ai.azure.openai.chat.options.deployment-name=gpt-4o
#spring.ai.azure.openai.chat.options.temperature=0.7

#spring.ai.vertex.ai.gemini.project-id=PROJECT_ID
#spring.ai.vertex.ai.gemini.location=LOCATION
#spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.0-flash
#spring.ai.vertex.ai.gemini.chat.options.temperature=0.5